require("defaults")

-- hl.on("hyprland.start", function()
-- 	hl.exec_cmd("waypaper --restore")
-- 	hl.exec_cmd("swaync")
-- 	hl.exec_cmd("waybar")
-- 	hl.exec_cmd("elephant")
-- 	hl.exec_cmd("walker --gapplication-service")
-- 	hl.exec_cmd("rambox")
-- 	hl.exec_cmd("spotify")
-- end)

-- hl.on("hyprland.start", function()
-- 	hl.exec_cmd("rambox")
-- 	hl.exec_cmd("spotify")
-- end)

hl.on("hyprland.start", function()
	hl.exec_cmd("hyprpm reload")
end)
