-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "eDP-1", mode = "1920x1080@144.00", position = "0x32", scale = 1.00 })
hl.monitor({ output = "HDMI-A-2", mode = "1024x768@60.00", position = "1920x0", scale = 2.00, mirror = "eDP-1" })
